import {
    Loader2,
    Github,
    Chrome,
    User,
    Mail,
    Lock,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    MoreVertical,
    Trash,
    Plus,
    Settings,
    LogOut,
    Menu,
    X,
    Calendar,
    DollarSign,
    CreditCard,
    Sparkles,
    RefreshCw,
    Clock,
    MessageSquare,
    type Icon as LucideIcon,
} from 'lucide-react'

export type Icon = typeof LucideIcon

export const Icons = {
    spinner: Loader2,
    google: Chrome,
    gitHub: Github,
    user: User,
    mail: Mail,
    lock: Lock,
    arrowRight: ArrowRight,
    check: Check,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    ellipsis: MoreVertical,
    trash: Trash,
    add: Plus,
    settings: Settings,
    logout: LogOut,
    menu: Menu,
    close: X,
    calendar: Calendar,
    billing: CreditCard,
    dollarSign: DollarSign,
    ai: Sparkles,
    sparkles: Sparkles,
    refresh: RefreshCw,
    clock: Clock,
    messageSquare: MessageSquare,
}
